/// Tiny localization engine: all user-facing strings in 8 languages.
/// No plugin, no files - one map, fully offline.
class L {
  L._();

  static String current = 'en';

  static const List<String> langs = <String>[
    'en',
    'es',
    'fr',
    'de',
    'pt',
    'it',
    'ja',
    'hi',
  ];

  static const Map<String, String> nativeNames = <String, String>{
    'en': 'English',
    'es': 'Español',
    'fr': 'Français',
    'de': 'Deutsch',
    'pt': 'Português',
    'it': 'Italiano',
    'ja': '日本語',
    'hi': 'हिंदी',
  };

  static const Map<String, String> flags = <String, String>{
    'en': '🇺🇸',
    'es': '🇪🇸',
    'fr': '🇫🇷',
    'de': '🇩🇪',
    'pt': '🇧🇷',
    'it': '🇮🇹',
    'ja': '🇯🇵',
    'hi': '🇮🇳',
  };

  /// Translate [key] into the current language (English fallback).
  static String t(String key) {
    final Map<String, String>? row = kStrings[key];
    if (row == null) return key;
    return row[current] ?? row['en'] ?? key;
  }

  /// Localized mode name, e.g. L.modeName(0) -> "Jigsaw" / "Rompecabezas".
  static String modeName(int mode) => t('mode_$mode');
}

/// Every string in the app. CI test asserts all 8 languages exist per key.
const Map<String, Map<String, String>> kStrings = <String, Map<String, String>>{
  'tagline': <String, String>{
    'en': 'Little puzzles, big fun!',
    'es': '¡Pequeños puzzles, gran diversión!',
    'fr': 'Petits puzzles, grands jeux !',
    'de': 'Kleine Puzzles, großer Spaß!',
    'pt': 'Pequenos quebra-cabeças, grande diversão!',
    'it': 'Piccoli puzzle, grande divertimento!',
    'ja': 'ちいさなパズル、おおきなたのしみ！',
    'hi': 'छोटे पज़ल, बड़ा मज़ा!',
  },
  'stickers': <String, String>{
    'en': 'Stickers',
    'es': 'Pegatinas',
    'fr': 'Autocollants',
    'de': 'Sticker',
    'pt': 'Adesivos',
    'it': 'Adesivi',
    'ja': 'シール',
    'hi': 'स्टिकर',
  },
  'stickerBook': <String, String>{
    'en': 'Sticker Book',
    'es': 'Álbum de pegatinas',
    'fr': "Livre d'autocollants",
    'de': 'Stickerbuch',
    'pt': 'Álbum de adesivos',
    'it': 'Libro degli adesivi',
    'ja': 'シールブック',
    'hi': 'स्टिकर बुक',
  },
  'parents': <String, String>{
    'en': 'Parents',
    'es': 'Padres',
    'fr': 'Parents',
    'de': 'Eltern',
    'pt': 'Pais',
    'it': 'Genitori',
    'ja': 'おとなのかたへ',
    'hi': 'अभिभावक',
  },
  'howToPlay': <String, String>{
    'en': 'Watch and play!',
    'es': '¡Mira y juega!',
    'fr': 'Regarde et joue !',
    'de': 'Schau und spiel!',
    'pt': 'Olhe e jogue!',
    'it': 'Guarda e gioca!',
    'ja': 'みて やってみよう！',
    'hi': 'देखो और खेलो!',
  },
  'guideDone': <String, String>{
    'en': 'Got it!',
    'es': '¡Entendido!',
    'fr': 'Compris !',
    'de': 'Verstanden!',
    'pt': 'Entendi!',
    'it': 'Capito!',
    'ja': 'わかった！',
    'hi': 'समझ गया!',
  },
  'winTitle': <String, String>{
    'en': 'Great job! 🎉',
    'es': '¡Buen trabajo! 🎉',
    'fr': 'Bravo ! 🎉',
    'de': 'Super gemacht! 🎉',
    'pt': 'Muito bem! 🎉',
    'it': 'Bravissimo! 🎉',
    'ja': 'やったね！🎉',
    'hi': 'शाबाश! 🎉',
  },
  'levelComplete': <String, String>{
    'en': 'Level @ complete',
    'es': 'Nivel @ completado',
    'fr': 'Niveau @ terminé',
    'de': 'Level @ geschafft',
    'pt': 'Nível @ completo',
    'it': 'Livello @ completato',
    'ja': 'レベル@ クリア',
    'hi': 'लेवल @ पूरा!',
  },
  'replay': <String, String>{
    'en': 'Replay',
    'es': 'Otra vez',
    'fr': 'Rejouer',
    'de': 'Nochmal',
    'pt': 'De novo',
    'it': 'Ancora',
    'ja': 'もういちど',
    'hi': 'फिर से',
  },
  'next': <String, String>{
    'en': 'Next',
    'es': 'Siguiente',
    'fr': 'Suivant',
    'de': 'Weiter',
    'pt': 'Próximo',
    'it': 'Avanti',
    'ja': 'つぎへ',
    'hi': 'आगे',
  },
  'menu': <String, String>{
    'en': 'Menu',
    'es': 'Menú',
    'fr': 'Menu',
    'de': 'Menü',
    'pt': 'Menu',
    'it': 'Menu',
    'ja': 'メニュー',
    'hi': 'मेनू',
  },
  'dailyChest': <String, String>{
    'en': 'Daily Chest!',
    'es': '¡Cofre diario!',
    'fr': 'Coffre du jour !',
    'de': 'Tägliche Truhe!',
    'pt': 'Baú diário!',
    'it': 'Forziere del giorno!',
    'ja': 'まいにちチェスト！',
    'hi': 'रोज़ का खज़ाना!',
  },
  'allStickers': <String, String>{
    'en': 'All stickers unlocked! 🎉',
    'es': '¡Todas las pegatinas desbloqueadas! 🎉',
    'fr': 'Tous les autocollants débloqués ! 🎉',
    'de': 'Alle Sticker freigeschaltet! 🎉',
    'pt': 'Todos os adesivos desbloqueados! 🎉',
    'it': 'Tutti gli adesivi sbloccati! 🎉',
    'ja': 'シールぜんぶゲット！🎉',
    'hi': 'सारे स्टिकर अनलॉक! 🎉',
  },
  'newSticker': <String, String>{
    'en': 'New sticker: @',
    'es': 'Nueva pegatina: @',
    'fr': 'Nouvel autocollant : @',
    'de': 'Neuer Sticker: @',
    'pt': 'Novo adesivo: @',
    'it': 'Nuovo adesivo: @',
    'ja': 'あたらしいシール: @',
    'hi': 'नया स्टिकर: @',
  },
  'yay': <String, String>{
    'en': 'Yay!',
    'es': '¡Sí!',
    'fr': 'Youpi !',
    'de': 'Juhu!',
    'pt': 'Oba!',
    'it': 'Evviva!',
    'ja': 'やったー！',
    'hi': 'ये हे!',
  },
  'parentsOnly': <String, String>{
    'en': 'Parents only',
    'es': 'Solo padres',
    'fr': 'Réservé aux parents',
    'de': 'Nur für Eltern',
    'pt': 'Só para pais',
    'it': 'Solo genitori',
    'ja': 'おとなのかただけ',
    'hi': 'सिर्फ़ अभिभावक',
  },
  'solveToContinue': <String, String>{
    'en': 'Solve this to continue',
    'es': 'Resuelve para continuar',
    'fr': 'Résous pour continuer',
    'de': 'Löse zum Fortfahren',
    'pt': 'Resolva para continuar',
    'it': 'Risolvi per continuare',
    'ja': 'こたえてね',
    'hi': 'जारी रखने के लिए हल करें',
  },
  'cancel': <String, String>{
    'en': 'Cancel',
    'es': 'Cancelar',
    'fr': 'Annuler',
    'de': 'Abbrechen',
    'pt': 'Cancelar',
    'it': 'Annulla',
    'ja': 'キャンセル',
    'hi': 'रद्द करें',
  },
  'totalStars': <String, String>{
    'en': 'Total stars',
    'es': 'Estrellas totales',
    'fr': 'Étoiles totales',
    'de': 'Sterne gesamt',
    'pt': 'Estrelas totais',
    'it': 'Stelle totali',
    'ja': 'ほしのかず',
    'hi': 'कुल सितारे',
  },
  'dayStreak': <String, String>{
    'en': 'Day streak',
    'es': 'Racha diaria',
    'fr': 'Série de jours',
    'de': 'Tages-Serie',
    'pt': 'Sequência diária',
    'it': 'Serie di giorni',
    'ja': 'れんぞく',
    'hi': 'लगातार दिन',
  },
  'playTime': <String, String>{
    'en': 'Play time',
    'es': 'Tiempo de juego',
    'fr': 'Temps de jeu',
    'de': 'Spielzeit',
    'pt': 'Tempo de jogo',
    'it': 'Tempo di gioco',
    'ja': 'あそんだじかん',
    'hi': 'खेलने का समय',
  },
  'progressByGame': <String, String>{
    'en': 'Progress by game',
    'es': 'Progreso por juego',
    'fr': 'Progrès par jeu',
    'de': 'Fortschritt pro Spiel',
    'pt': 'Progresso por jogo',
    'it': 'Progressi per gioco',
    'ja': 'ゲームごとのせいせき',
    'hi': 'गेम-wise प्रगति',
  },
  'privacyText': <String, String>{
    'en': 'This app works fully offline. No ads, no accounts, no internet, no analytics. All progress stays on this device only. Nothing is collected or shared.',
    'es': 'Esta app funciona sin internet. Sin anuncios, sin cuentas, sin analíticas. Todo el progreso se queda solo en este dispositivo. No se recoge ni se comparte nada.',
    'fr': "Cette app fonctionne hors ligne. Pas de pubs, pas de comptes, pas d'analyse. Toute la progression reste sur cet appareil. Rien n'est collecté ni partagé.",
    'de': 'Diese App funktioniert komplett offline. Keine Werbung, keine Konten, keine Analysen. Der gesamte Fortschritt bleibt nur auf diesem Gerät. Nichts wird gesammelt oder geteilt.',
    'pt': 'Este app funciona totalmente offline. Sem anúncios, sem contas, sem análises. Todo o progresso fica apenas neste dispositivo. Nada é coletado ou compartilhado.',
    'it': 'Questa app funziona completamente offline. Niente pubblicità, niente account, niente analisi. Tutti i progressi restano solo su questo dispositivo. Nulla viene raccolto o condiviso.',
    'ja': 'このアプリは完全にオフラインで動きます。広告なし、アカウントなし、解析なし。進行はすべてこの端末だけに保存されます。収集も共有もされません。',
    'hi': 'यह ऐप पूरी तरह ऑफ़लाइन चलता है। कोई विज्ञापन नहीं, कोई अकाउंट नहीं, कोई एनालिटिक्स नहीं। सारी प्रगति सिर्फ़ इसी डिवाइस पर रहती है। कुछ भी इकट्ठा या साझा नहीं किया जाता।',
  },
  'version': <String, String>{
    'en': 'Version',
    'es': 'Versión',
    'fr': 'Version',
    'de': 'Version',
    'pt': 'Versão',
    'it': 'Versione',
    'ja': 'バージョン',
    'hi': 'संस्करण',
  },
  'resetProgress': <String, String>{
    'en': 'Reset progress',
    'es': 'Reiniciar progreso',
    'fr': 'Réinitialiser',
    'de': 'Fortschritt löschen',
    'pt': 'Redefinir progresso',
    'it': 'Azzera progressi',
    'ja': 'リセット',
    'hi': 'प्रगति रीसेट',
  },
  'resetTitle': <String, String>{
    'en': 'Reset all progress?',
    'es': '¿Reiniciar todo el progreso?',
    'fr': 'Tout réinitialiser ?',
    'de': 'Gesamten Fortschritt löschen?',
    'pt': 'Redefinir todo o progresso?',
    'it': 'Azzerare tutti i progressi?',
    'ja': 'すべてリセットする？',
    'hi': 'सारी प्रगति रीसेट करें?',
  },
  'resetBody': <String, String>{
    'en': 'Stars, stickers and streak will be erased from this device. This cannot be undone.',
    'es': 'Las estrellas, pegatinas y la racha se borrarán de este dispositivo. No se puede deshacer.',
    'fr': 'Les étoiles, autocollants et la série seront effacés de cet appareil. Action irréversible.',
    'de': 'Sterne, Sticker und Serie werden von diesem Gerät gelöscht. Das kann nicht rückgängig gemacht werden.',
    'pt': 'Estrelas, adesivos e a sequência serão apagados deste dispositivo. Isso não pode ser desfeito.',
    'it': 'Stelle, adesivi e serie verranno cancellati da questo dispositivo. Non si può annullare.',
    'ja': 'ほし・シール・れんぞくがこの端末から消えます。もとには戻せません。',
    'hi': 'सितारे, स्टिकर और स्ट्रीक इस डिवाइस से मिट जाएंगे। इसे वापस नहीं लाया जा सकता।',
  },
  'reset': <String, String>{
    'en': 'Reset',
    'es': 'Reiniciar',
    'fr': 'Réinitialiser',
    'de': 'Löschen',
    'pt': 'Redefinir',
    'it': 'Azzera',
    'ja': 'リセット',
    'hi': 'रीसेट',
  },
  'chooseLanguage': <String, String>{
    'en': 'Choose your language',
    'es': 'Elige tu idioma',
    'fr': 'Choisis ta langue',
    'de': 'Wähle deine Sprache',
    'pt': 'Escolha seu idioma',
    'it': 'Scegli la tua lingua',
    'ja': 'ことばをえらんでね',
    'hi': 'अपनी भाषा चुनें',
  },
  'language': <String, String>{
    'en': 'Language',
    'es': 'Idioma',
    'fr': 'Langue',
    'de': 'Sprache',
    'pt': 'Idioma',
    'it': 'Lingua',
    'ja': 'ことば',
    'hi': 'भाषा',
  },
  'mode_0': <String, String>{
    'en': 'Jigsaw',
    'es': 'Rompecabezas',
    'fr': 'Puzzle',
    'de': 'Puzzle',
    'pt': 'Quebra-cabeça',
    'it': 'Puzzle',
    'ja': 'ジグソー',
    'hi': 'जिग्सॉ',
  },
  'mode_1': <String, String>{
    'en': 'Shadow Match',
    'es': 'Sombras',
    'fr': 'Ombres',
    'de': 'Schatten',
    'pt': 'Sombras',
    'it': 'Ombre',
    'ja': 'かげあそび',
    'hi': 'परछाई',
  },
  'mode_2': <String, String>{
    'en': 'Memory Pairs',
    'es': 'Memoria',
    'fr': 'Mémoire',
    'de': 'Memory',
    'pt': 'Memória',
    'it': 'Memory',
    'ja': 'ねあわせ',
    'hi': 'मेमोरी',
  },
  'mode_3': <String, String>{
    'en': 'Feed Me',
    'es': 'Aliméntalos',
    'fr': 'À table !',
    'de': 'Füttern',
    'pt': 'Alimenta',
    'it': 'Pappa!',
    'ja': 'えさやり',
    'hi': 'भोजन दो',
  },
  'mode_4': <String, String>{
    'en': 'Odd One Out',
    'es': 'El diferente',
    'fr': "L'intrus",
    'de': 'Das falsche Tier',
    'pt': 'O diferente',
    'it': "L'intruso",
    'ja': 'ちがうのはどれ？',
    'hi': 'अलग वाला',
  },
  'mode_5': <String, String>{
    'en': 'Size Line-Up',
    'es': 'De menor a mayor',
    'fr': 'Du plus petit au plus grand',
    'de': 'Der Größe nach',
    'pt': 'Do menor ao maior',
    'it': 'Dal più piccolo',
    'ja': 'ちいさいじゅん',
    'hi': 'छोटे से बड़ा',
  },
  'mode_6': <String, String>{
    'en': 'Pattern Train',
    'es': 'Tren de patrones',
    'fr': 'Train des motifs',
    'de': 'Musterzug',
    'pt': 'Trem de padrões',
    'it': 'Treno dei disegni',
    'ja': 'パターントレイン',
    'hi': 'पैटर्न ट्रेन',
  },
  'mode_7': <String, String>{
    'en': 'Count & Tap',
    'es': 'Cuenta y toca',
    'fr': 'Compte et touche',
    'de': 'Zählen & Tippen',
    'pt': 'Conta e toca',
    'it': 'Conta e tocca',
    'ja': 'かぞえてタップ',
    'hi': 'गिनो और टैप',
  },
  'guide_0': <String, String>{
    'en': 'Put the pieces in the right place!',
    'es': '¡Pon las piezas en su lugar!',
    'fr': 'Place les pièces au bon endroit !',
    'de': 'Lege die Teile an die richtige Stelle!',
    'pt': 'Coloque as peças no lugar certo!',
    'it': 'Metti i pezzi al posto giusto!',
    'ja': 'ピースを ただしいばしょに いれよう！',
    'hi': 'पीस को सही जगह लगाओ!',
  },
  'guide_1': <String, String>{
    'en': 'Find the matching shadow!',
    'es': '¡Encuentra la sombra correcta!',
    'fr': 'Trouve la bonne ombre !',
    'de': 'Finde den passenden Schatten!',
    'pt': 'Ache a sombra certa!',
    'it': "Trova l'ombra giusta!",
    'ja': 'おなじ かげを さがそう！',
    'hi': 'सही परछाई ढूंढो!',
  },
  'guide_2': <String, String>{
    'en': 'Flip the cards and find the pairs!',
    'es': '¡Voltea las cartas y encuentra las parejas!',
    'fr': 'Retourne les cartes et trouve les paires !',
    'de': 'Decke die Karten auf und finde die Paare!',
    'pt': 'Vire as cartas e ache os pares!',
    'it': 'Gira le carte e trova le coppie!',
    'ja': 'カードを めくって ペアを さがそう！',
    'hi': 'कार्ड पलटो और जोड़ी ढूंढो!',
  },
  'guide_3': <String, String>{
    'en': 'Give each animal its favorite food!',
    'es': '¡Dale a cada animal su comida favorita!',
    'fr': 'Donne à chaque animal sa nourriture préférée !',
    'de': 'Gib jedem Tier sein Lieblingsfutter!',
    'pt': 'Dê a cada animal sua comida favorita!',
    'it': 'Dai a ogni animale il suo cibo preferito!',
    'ja': 'どうぶつに すきな たべものを あげよう！',
    'hi': 'हर जानवर को उसकी पसंदीदा चीज़ दो!',
  },
  'guide_4': <String, String>{
    'en': 'Tap the animal that is different!',
    'es': '¡Toca el animal diferente!',
    'fr': "Touche l'animal différent !",
    'de': 'Tippe auf das andere Tier!',
    'pt': 'Toque no animal diferente!',
    'it': "Tocca l'animale diverso!",
    'ja': 'ちがう どうぶつを タップ！',
    'hi': 'अलग जानवर पर टैप करो!',
  },
  'guide_5': <String, String>{
    'en': 'Tap from smallest to biggest!',
    'es': '¡Toca del más pequeño al más grande!',
    'fr': 'Touche du plus petit au plus grand !',
    'de': 'Tippe vom kleinsten zum größten!',
    'pt': 'Toque do menor para o maior!',
    'it': 'Tocca dal più piccolo al più grande!',
    'ja': 'ちいさい じゅんに タップ！',
    'hi': 'सबसे छोटे से सबसे बड़े तक टैप करो!',
  },
  'guide_6': <String, String>{
    'en': 'Finish the pattern train!',
    'es': '¡Completa el tren de patrones!',
    'fr': 'Termine le train des motifs !',
    'de': 'Vervollständige den Musterzug!',
    'pt': 'Complete o trem de padrões!',
    'it': 'Completa il treno dei disegni!',
    'ja': 'パターンを つづけよう！',
    'hi': 'पैटर्न ट्रेन पूरी करो!',
  },
  'guide_7': <String, String>{
    'en': 'Count the animals and tap the number!',
    'es': '¡Cuenta los animales y toca el número!',
    'fr': 'Compte les animaux et touche le nombre !',
    'de': 'Zähle die Tiere und tippe die Zahl!',
    'pt': 'Conte os animais e toque no número!',
    'it': 'Conta gli animali e tocca il numero!',
    'ja': 'どうぶつを かぞえて すうじを タップ！',
    'hi': 'जानवर गिनो और सही नंबर टैप करो!',
  },
};
